import os, sys, re, argparse, time
import requests
from glob import glob
from getpass import getpass
from mastodon import Mastodon
from markdown import markdown
from html_text import extract_text

RE_MENTION = re.compile(r'@(\w+)@([\w.]+)')

def get_mentions(s, ignore=None):
    mentions = set([
        "@{}@{}".format(user,instance)
        for user, instance in RE_MENTION.findall(s)])
    if ignore:
        mentions -= get_mentions(ignore)
    return mentions

def linkify_mentions(s):
    return RE_MENTION.sub(
        lambda m:
            "[@{user}](https://{instance}/@{user})".format(
                user=m.group(1), instance=m.group(2)),
        s)

def make_gist(title, body):
    return requests.post(
        "https://api.github.com/gists",
        json={
            "description": title,
            "public": True,
            "files": {
                "TOOT.md": {
                    "content": "### {}\n\n{}".format(title, body)
                }
            }
        }
    ).json()['html_url']+"#file-toot-md"

if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description="Toot stdin as a gist [markdown is supported].")
    parser.add_argument('--title', '-t',
                        help="Optional: gist's title, and the toot's content warning (CW).")
    parser.add_argument('--instance', '-i',
                        help='Your mastodon instance (e.g. mastodon.social).')
    parser.add_argument('--email', '-e',
                        help='The email address you login to that instance with.')
    parser.add_argument('--app_name', '-a', default='Gistodon',
                        help='Name for the app (default is Gistodon).')
    args = parser.parse_args()
    lines = sys.stdin.readlines()
    assert len(filter(lambda l: l.strip(), lines)), \
        "Empty toot."
    body = '\n'.join(lines)
    assert not args.title or len(args.title)<=80, "Title exceeds 80 characters"
    summary = extract_text(markdown(body.strip()[:140]))
    instance = args.instance
    if instance:
        client_cred_filename = '{}.{}.client.secret'.format(args.app_name, args.instance)
    else:
        candidates = glob('{}.*.client.secret'.format(args.app_name))
        assert candidates, "No app/user registered. Please run register.sh first."
        client_cred_filename = candidates[0]
        instance = client_cred_filename[len(args.app_name)+1:-len('.client.secret')]
    email = args.email
    if email:
        user_cred_filename = '{}.{}.{}.user.secret'.format(
            args.app_name, instance, email.replace('@','.'))
    else:
        candidates = glob('{}.{}.*.user.secret'.format(
            args.app_name, instance))
        assert len(candidates), \
            "No user registered for {} at {}. Please run register.sh first.".format(
                args.app_name, instance)
        user_cred_filename = candidates[0]
    assert \
        os.path.exists(client_cred_filename) and \
            os.path.exists(user_cred_filename), \
        "App/user not registered. Please run register.sh"
    masto = Mastodon(
        client_id = client_cred_filename,
        access_token = user_cred_filename,
        api_base_url = 'https://'+instance)
    status = '{}... {}'.format(summary,
        make_gist(
            args.title or "A gistodon toot, {} GMT".format(
                time.asctime(time.gmtime())),
            linkify_mentions(body)+ """

###### Generated by [Gistodon](https://github.com/thedod/gistodon/#readme)."""))
    mentions = get_mentions(body, ignore=summary)
    if mentions:
        status += '\n'+' '.join(mentions)
    print masto.status_post(status, spoiler_text=args.title)['url']
